// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/CoderSamYhc/learn-go-zero/apps/app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: ApiHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/order/list",
				Handler: OrderListHandler(serverCtx),
			},
		},
	)
}
