// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type Product struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Stock       string `json:"stock"`
	Price       int64  `json:"price"`
	Category    string `json:"category"`
	Status      int8   `json:"status"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type ProductListResponse struct {
	Products []*Product `json:"products"`
	Size     int8       `json:"size"`
	Page     int8       `json:"page"`
	Total    int8       `json:"total"`
}

type ProductListRequest struct {
	Size int8 `json:"size"`
	Page int8 `json:"page"`
}
